version: '3.8'


service:
  image: 'ngnix:stable-alpine'
  ports:
    - '8000:80'
  volumes:
    - ./ngnix/ngnix.conf:/etc/ngnix/ngnix.conf:ro


  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:deledated


  mysql:
    image: mysql:5.7 
    env_file:
      - ./env/mysql.env
  composer:
  artisam:
  npm: