version: '3.8'

services:
  frontend:
    image: 'frontend'
    ports:
      - '3000:3000'
    networks:
      - default
  backend:
    image: 'backend'
    ports:
      - '8000:8000'
    networks:
      - default
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongoDB:27017
  mongoDB:
    image: 'mongoDB'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }}
      - MONGO_INITDB_ROOT_PASSWORD={{ MONGO_INITDB_ROOT_PASSWORD }}
    ports:
      - '27017:27017'


networks:
  default:
    driver: bridge

volumes:
  mongo-data:
    
      
    


