services:
  frontend:
    build:
      context: ./frontend
    image: frontend
    command: ["npm", "run","dev"]
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - default

  backend:
    build:
      context: ./backend
    image: backend
    command: ["node", "index.js"]
    ports:
      - '8000:8000'
    volumes:
       - logs:/app/logs
    environment:
      - MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }}
      - MONGO_INITDB_ROOT_PASSWORD={{ MONGO_INITDB_ROOT_PASSWORD }}
    depends_on:
      - mongodb
    env_file:
      - ./.env
    networks:
      - default

    # environment:
      # - MONGO_URI=mongodb://admin:admin123@mongoDB:27017


  mongodb:
    build:
      context: ./mongodb
    image: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'


networks:
  default:
    driver: bridge

volumes:
  mongo-data:
  logs:
    
      
    


